package com.iqonic.shophop;

public class Constants {

    // DEV
    //public final static String FIREBASE_INTEGRATION_KEY = "ndj5b5osGdCwjqu6FzYixe7RNlxX6iTyaZvhjuvQKamLWMoOp3TOjC6Cu_s_l_CoVOGLTq2uRe5Pbj3K1q56qZv1E0ZPoXtzThp9_p_l_Lqt2YIar5_s_l_JIEP8oQHhd4_s_l_LvtxoTGzyaJCxz0JbVSych38gG2QDrQ_e_q__e_q_";
    //public final static String HUAWEI_INTEGRATION_KEY = "WOUGDDPgg_s_l_tmdWUvHo2LFGMQJEwM2KJOMoDwn58BQI3oh_s_l_ZiykaJEmL5GzqzUSbyexhSNmrt5Pj30CYr4QijVNpX0fahhHGOy7lpqeo4PvIOACL_p_l_s20CZNa359vLbDTZA5GUCRfBbnn78MrdGl7oKg_e_q__e_q_";

    // TEST
    public final static String FIREBASE_INTEGRATION_KEY = "UHun4lQBPZil5g15DhilNsH0YFkbqeQrs0qRnvZfs7jz0yd0Bvb1i6aOct9asp2k5sDFLmWErxot8lGIb3K3sAuwp2ESYvQ1Vj7t_s_l_CeJ3jnaHO1YL7SiXt7L1gx4H69p";
    public final static String HUAWEI_INTEGRATION_KEY = "6Q4LkrIY_p_l_T2Oe_s_l_g_s_l_luRItKt1sTr_p_l_7WVKlH9w8_s_l_xZRS3G9aVPRkU0fsrhTe4dYeKoJNFYPZgdYTRiftnxj6EHTxT4JphTAHBMLUcGvKz0Gzmp5_s_l_sTM0lMiJyfD2t9XPTX";
}
